### PR TITLE
Update vote.py

### PR DESCRIPTION
**Pull request by freeze11**
you probably know what im trying to do. Im not sure what to do next

### CODE REVIEW

**Comment by dado3212** [comment]
Just run it.  I'm not going to merge in your specific poll.

**Comment by freeze11** [comment]
not sure how to run it. can you help ?

**Comment by freeze11** [comment]
can you run it for me? with those numbers? Its for my niece. very good
pitcher at a small highschool

**Comment by freeze11** [comment]
the big schools have an advantage. Ive got you

**Comment by freeze11** [comment]
I pull tits for a living. Im surprised I got this far

**Pull request closed without merging**
